name = "edcloudwasm"
main = "_worker.js"
compatibility_date = "2026-05-12"

[vars]
UUID = "d35c982c-63e9-4fca-b08f-90870bb33fbe"
PASSWORD = "ytmn"
SSPASS = "ytmn"
S5HTTPUSER = "admin"
S5HTTPPASS = "254613"

[limits]
cpu_ms = 300000
